"""
Django settings for easycart_project project.

Generated by 'django-admin startproject' using Django 4.2.26.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-m1(g%mz7^2kj(8%qwqc!lfhs1d)u-#==m-00&9#^!ckp3!e&3z'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    '79598be562514c25bb443db7a0a15de2.vfs.cloud9.us-east-1.amazonaws.com',
    'localhost',
    '127.0.0.1'
    ]
CSRF_TRUSTED_ORIGINS = [
    "https://79598be562514c25bb443db7a0a15de2.vfs.cloud9.us-east-1.amazonaws.com"
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'store'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'easycart_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'easycart_project.context_processors.global_settings', 
            ],
        },
    },
]

WSGI_APPLICATION = 'easycart_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import os
import json
import boto3
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent

CONFIG_FILE = os.path.join(BASE_DIR, "infra", "config.json")

with open(CONFIG_FILE) as f:
    infra_config = json.load(f)

# ====== Cognito ======
COGNITO = {
    "region": infra_config.get("region"),
    "user_pool_id": infra_config.get("user_pool_id"),
    "app_client_id": infra_config.get("app_client_id"),
    "domain_url": infra_config.get("domain_url"),
    # ⭐ add lambda cart endpoints here
    "lambda_cart_endpoints": infra_config.get("lambda_cart_endpoints", {}),
    "rate_limit": infra_config.get("rate_limit", {})
    
}

# ====== S3 Settings ======
S3_BUCKET = "easycart-proj-nci"
S3_REGION = infra_config.get("region")
S3_LOGO_KEY = "images/EasyCartLogo.png"      # FIXED — must be an S3 key, not a URL


def generate_presigned_logo_url():
    s3 = boto3.client("s3", region_name=S3_REGION)
    try:
        return s3.generate_presigned_url(
            ClientMethod="get_object",
            Params={"Bucket": S3_BUCKET, "Key": S3_LOGO_KEY},
            ExpiresIn=3600
        )
    except Exception as e:
        print("Error generating presigned URL:", e)
        return ""


# (Optional) Generate once on startup
SIGNED_LOGO_URL = generate_presigned_logo_url()

SESSION_ENGINE = "django.contrib.sessions.backends.db"


DEV_MODE = infra_config.get("dev_mode", False)

PRODUCT_TABLES = ["Phones", "Laptops", "Accessories"]

RATE_LIMIT_LOGIN_LIMIT = COGNITO["rate_limit"]["login"]["limit"]
RATE_LIMIT_LOGIN_WINDOW = COGNITO["rate_limit"]["login"]["window"]
